source 'http://rubygems.org'

gem 'rake', '0.8.7'
gem 'rails', '3.0.6'
gem 'sqlite3'
gem 'capistrano-ext'
gem 'heroku'
gem 'mysql', '2.8.1'

group :development, :test do
  gem 'ruby-debug'
  gem 'rspec-rails'
  gem 'ZenTest', '4.4.2'
end
